### PR TITLE
added React Context to project, badge functionality

### PR DESCRIPTION
**Pull request by coreycarmichael**
Added React Context for adding to cart functionality

### CODE REVIEW

**Review by BevBuCodes — APPROVED** [review]
Great work!

**Comment by Greenhouse89** [comment]
This is a big win. Way less steps involved than Redux

**Review by bvoncarr — APPROVED** [review]
Great Job Playa!!!

**Review by Greenhouse89 — COMMENTED** [review]
Way better than redux.

**Pull request merged**
